# These are supported funding model platforms

github: @Neoplays26yt, @akshathdomino 
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: # Replace with a single thanks.dev username
custom: https://www.bing.com/ck/a?!&&p=460904818cc67827483ced413d5fc9eed76cb01038dbba799eddc2a443545557JmltdHM9MTc4MTkxMzYwMA&ptn=3&ver=2&hsh=4&fclid=0b7439bf-b4ad-6771-36c3-2effb5a66679&psq=weeklyhow+on+youtube&u=a1aHR0cHM6Ly93d3cueW91dHViZS5jb20vV2Vla2x5SG93
