import json
import re
import random as _random
import urllib.request
import urllib.error
from datetime import datetime
from typing import Dict, Any, List
from .heuristic import HeuristicEngine

class ModelResponse:
    def __init__(self, text: str, tools_to_call: List[Dict[str, Any]] = None):
        self.text = text
        self.tools_to_call = tools_to_call or []

class ModelEngine:
    def __init__(self, config):
        self.config = config

    def query(self, prompt: str, system_context: str = "") -> ModelResponse:
        import re
        backend = self.config.backend.lower()
        
        # Check for web scraping/search intent
        p_low = prompt.lower()
        web_context = ""
        
        # 1. Direct Scrape Intent
        url_match = re.search(r'https?://[^\s]+', prompt)
        if "scrape" in p_low and url_match:
            url = url_match.group(0)
            from ulolm.scraper import WebScraper
            scraped_content = WebScraper.scrape_url(url)
            web_context = f"\n\nSCRAPED CONTENT FROM {url}:\n{scraped_content}"
            
        # 2. Web Search Intent
        elif "search" in p_low or "look up" in p_low:
            search_query = prompt
            for word in ["search for", "search", "look up"]:
                if p_low.startswith(word):
                    search_query = prompt[len(word):].strip()
                    break
            
            from ulolm.scraper import WebScraper
            search_results = WebScraper.search(search_query)
            if search_results:
                results_str = "\n".join([
                    f"- Title: {r['title']}\n  Snippet: {r['snippet']}\n  URL: {r['url']}"
                    for r in search_results
                ])
                web_context = f"\n\nWEB SEARCH RESULTS FOR '{search_query}':\n{results_str}"
                
        if web_context:
            system_context = f"{system_context}\n\n{web_context}"

        if backend == "ollama":
            return self._query_ollama(prompt, system_context)
        elif backend == "openai":
            return self._query_openai(prompt, system_context)
        elif backend == "gemini":
            return self._query_gemini(prompt, system_context)
        elif backend == "combined":
            return self._query_combined(prompt, system_context)
        else:
            return self._query_native(prompt, system_context)

    def _query_combined(self, prompt: str, system_context: str) -> ModelResponse:
        from .memory import ProjectMemory
        
        # --- EXTENSION 1 & 2: Heuristic Context & Wiki Retrieval ---
        memory = ProjectMemory(self.config.workspace_path)
        engine = HeuristicEngine()
        engine.load_training_data(memory.get_training_data())
        
        intent = engine.identify_intent(prompt)
        
        context_str = memory.search_context(prompt, engine)
        
        # Inject the retrieved context into the system_context
        if context_str and len(context_str.strip()) > 10:
            enhanced_system_context = f"{system_context}\n\nADDITIONAL HEURISTIC CONTEXT:\n{context_str}"
        else:
            enhanced_system_context = system_context
            
        # --- EXTENSION 3: Multi-model generation ---
        # Step 1: Query Gemini for the initial draft using the enhanced context
        gemini_response = self._query_gemini(prompt, enhanced_system_context)
        
        # If Gemini failed due to missing API keys or network errors, we can't combine.
        if not gemini_response.text or "Error" in gemini_response.text or "missing" in gemini_response.text:
            return ModelResponse(f"Combined Engine Failed during Gemini Step:\n{gemini_response.text}")
            
        # Step 2: Formulate the synthesis prompt for OpenAI
        synthesis_prompt = (
            f"Original User Prompt: {prompt}\n\n"
            f"Here is a draft response generated by a sub-model:\n"
            f"--- START DRAFT ---\n{gemini_response.text}\n--- END DRAFT ---\n\n"
            f"Please review this draft, fact-check it, improve it, and provide the final, synthesized, and perfect answer."
            f" Answer directly as yourself (UloLM)."
        )
        
        # Step 3: Query OpenAI to finalize the answer
        final_response = self._query_openai(synthesis_prompt, enhanced_system_context)
        if not final_response.text or "Error" in final_response.text or "missing" in final_response.text:
            return ModelResponse(f"Combined Engine Failed during OpenAI Step:\n{final_response.text}\n\nFallback Gemini Draft:\n{gemini_response.text}")
            
        return final_response

    def _query_ollama(self, prompt: str, system_context: str) -> ModelResponse:
        url = f"{self.config.ollama_url}/api/chat"
        model_name = "codellama" if self.config.active_model == "UloLMBase" else "phi3"
        payload = {"model": model_name, "messages": [
            {"role": "system", "content": system_context},
            {"role": "user", "content": prompt}
        ], "stream": False, "options": {"temperature": 0.2}}
        try:
            req = urllib.request.Request(url, data=json.dumps(payload).encode('utf-8'),
                headers={'Content-Type': 'application/json'})
            with urllib.request.urlopen(req, timeout=30) as resp:
                res = json.loads(resp.read().decode('utf-8'))
                return self._parse_response(res.get("message", {}).get("content", ""))
        except urllib.error.URLError as e:
            return ModelResponse(f"Error connecting to Ollama: {e.reason}.\nMake sure Ollama is running at {self.config.ollama_url}.")
        except Exception as e:
            return ModelResponse(f"Ollama query failed: {e}")

    def _query_openai(self, prompt: str, system_context: str) -> ModelResponse:
        if not self.config.openai_api_key:
            return ModelResponse("OpenAI API Key is missing. Set the OPENAI_API_KEY environment variable.")
        url = f"{self.config.openai_base_url}/chat/completions"
        payload = {"model": self.config.openai_model, "messages": [
            {"role": "system", "content": system_context},
            {"role": "user", "content": prompt}
        ], "temperature": 0.2}
        try:
            req = urllib.request.Request(url, data=json.dumps(payload).encode('utf-8'),
                headers={'Content-Type': 'application/json', 'Authorization': f'Bearer {self.config.openai_api_key}'})
            with urllib.request.urlopen(req, timeout=30) as resp:
                res = json.loads(resp.read().decode('utf-8'))
                return self._parse_response(res.get("choices", [{}])[0].get("message", {}).get("content", ""))
        except urllib.error.HTTPError as e:
            return ModelResponse(f"OpenAI API Error: {e.code} - {e.read().decode('utf-8')}")
        except Exception as e:
            return ModelResponse(f"OpenAI query failed: {e}")

    def _query_gemini(self, prompt: str, system_context: str) -> ModelResponse:
        if not self.config.gemini_api_key:
            return ModelResponse("Gemini API Key is missing. Set the GEMINI_API_KEY environment variable or run `/config gemini_api_key YOUR_KEY`.")
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.config.gemini_model}:generateContent?key={self.config.gemini_api_key}"
        
        # Format for Gemini
        parts = []
        if system_context:
            parts.append({"text": f"System Context:\n{system_context}\n\n"})
        parts.append({"text": prompt})
        
        payload = {
            "contents": [{"parts": parts}],
            "generationConfig": {"temperature": 0.2}
        }
        
        try:
            req = urllib.request.Request(url, data=json.dumps(payload).encode('utf-8'),
                headers={'Content-Type': 'application/json'})
            with urllib.request.urlopen(req, timeout=30) as resp:
                res = json.loads(resp.read().decode('utf-8'))
                
                # Extract text
                text = ""
                try:
                    candidates = res.get("candidates", [])
                    if candidates:
                        parts = candidates[0].get("content", {}).get("parts", [])
                        text = "".join(p.get("text", "") for p in parts)
                except Exception:
                    text = str(res)
                    
                return self._parse_response(text)
        except urllib.error.HTTPError as e:
            return ModelResponse(f"Gemini API Error: {e.code} - {e.read().decode('utf-8')}")
        except Exception as e:
            return ModelResponse(f"Gemini query failed: {e}")

    def _parse_response(self, text: str) -> ModelResponse:
        import re
        import json
        tools = []
        json_blocks = re.findall(r'```(?:json)?\s*([\s\S]*?)```', text)
        for block in json_blocks:
            try:
                data = json.loads(block)
                if isinstance(data, list):
                    for item in data:
                        if isinstance(item, dict) and "name" in item:
                            tools.append(item)
                elif isinstance(data, dict) and "name" in data:
                    tools.append(data)
                elif isinstance(data, dict) and "tools_to_call" in data:
                    tools.extend(data["tools_to_call"])
            except Exception:
                pass
        return ModelResponse(text, tools)

    def _pc(self, system_context: str) -> dict:
        """Parse context from system_context string."""
        ctx = {"project_name":"","tech_stack":"","files":[],"symbols":[],"roadmap_completed":[],"rp":[],"rt":[],"has":False}
        if not system_context:
            return ctx
        in_files = in_symbols = False
        for line in system_context.splitlines():
            s = line.strip()
            if s.startswith("Project Name:"):
                ctx["project_name"] = s.split(":", 1)[1].strip()
                if ctx["project_name"] and ctx["project_name"] != "Unnamed":
                    ctx["has"] = True
                in_files = in_symbols = False
            elif s.startswith("Target Stack:"):
                ctx["tech_stack"] = s.split(":", 1)[1].strip()
                in_files = in_symbols = False
            elif s == "Indexed Files:":
                in_files, in_symbols = True, False
            elif s == "Key Symbols Extracted:":
                in_files, in_symbols = False, True
            elif s.startswith("Roadmap:") or s.startswith("="):
                in_files = in_symbols = False
            elif s.startswith("- Completed:"):
                v = s.split(":", 1)[1].strip()
                if v and v != "None": ctx["roadmap_completed"] = [x.strip() for x in v.split(",")]
            elif s.startswith("- In Progress:"):
                v = s.split(":", 1)[1].strip()
                if v and v != "None": ctx["rp"] = [x.strip() for x in v.split(",")]
            elif s.startswith("- Todo:"):
                v = s.split(":", 1)[1].strip()
                if v and v != "None": ctx["rt"] = [x.strip() for x in v.split(",")]
            elif s.startswith("- "):
                entry = s[2:].strip()
                if in_files: ctx["files"].append(entry)
                elif in_symbols: ctx["symbols"].append(entry)
        return ctx

    def _search_wikipedia(self, query: str) -> str:
        """Fetches a summary from Wikipedia to act as an infinite knowledge base."""
        import urllib.parse
        try:
            # 1. Search for the exact page title
            q = urllib.parse.quote(query)
            search_url = f"https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch={q}&utf8=&format=json"
            req = urllib.request.Request(search_url, headers={'User-Agent': 'UloLM/2.0'})
            with urllib.request.urlopen(req, timeout=5) as resp:
                search_data = json.loads(resp.read().decode('utf-8'))
                
            if not search_data.get('query', {}).get('search'):
                return ""
                
            title = search_data['query']['search'][0]['title']
            
            # 2. Fetch the summary for that title
            t = urllib.parse.quote(title)
            summary_url = f"https://en.wikipedia.org/api/rest_v1/page/summary/{t}"
            req2 = urllib.request.Request(summary_url, headers={'User-Agent': 'UloLM/2.0'})
            with urllib.request.urlopen(req2, timeout=5) as resp2:
                summary_data = json.loads(resp2.read().decode('utf-8'))
                
            extract = summary_data.get('extract', '')
            if extract:
                return f"**From Wikipedia ({title}):**\n\n{extract}"
            return ""
        except Exception:
            return ""

    # ─────────────────────────────────────────────────────────────
    # Native Engine — GPT4All Local Inference
    # ─────────────────────────────────────────────────────────────

    def _query_native(self, prompt: str, system_context: str) -> ModelResponse:
        from .generative import GenerativeEngine
        
        # Initialize the native GPT4All generative engine
        engine = GenerativeEngine(self.config.workspace_path)
        
        # Generate text natively using local Phi-3 weights
        response_text = engine.generate(prompt, length=500, system_context=system_context)
        
        return self._parse_response(response_text)
